language: ruby
# Emacs fails to build in container-based builds on Travis
# See https://github.com/travis-ci/travis-ci/issues/9061
# and https://github.com/moby/moby/issues/22801
sudo: required
dist: trusty
# Allow Emacs snapshot builds to fail and don't wait for it
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
# Cache stable Emacs binaries and packages
cache:
  bundler: true
  apt: true
  directories:
      - "$HOME/emacs"
git:
  depth: 1
env:
  matrix:
    - EMACS_VERSION=24.3
    - EMACS_VERSION=24.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.1-rc2
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=26.2
    - EMACS_VERSION=snapshot
  global:
    # Maximum number of executing procesors
    - MAKE_JOBS=$(getconf _NPROCESSORS_ONLN)
before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
before_install:
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - if [[ -n $EMACS_VERSION ]]; then make -s -f emacs-travis.mk install_emacs; fi
  - if [[ -n $HOME/.cask ]]; then make -s -f emacs-travis.mk install_cask; fi
install:
  - make setup
script:
  - make test
